-- =========================================================================
-- check-sap-config.sql — READ-ONLY health check for SAP API Settings.
-- Generated by scripts/generate-sap-sync.py together with sync-sap-config.sql.
-- Changes nothing. Run before and after the sync:
--   docker exec -i supabase-db psql -U postgres -d postgres < scripts/check-sap-config.sql
-- Expected endpoints in the reference environment: 71
-- =========================================================================

\echo '== 1. API counts (expected total: 71) =='
select count(*) as total_apis,
       count(*) filter (where is_active) as active_apis,
       71 as expected_apis
from public.sap_api_configs;

\echo '== 2. Missing or inactive APIs (EMPTY = all present) =='
with expected(name, req_count, res_count) as (values
('90%_CUST_API',1,1),
('90%_CUSTNAME_API',1,1),
('BMW_Status_Report',9,42),
('Contract_Approval_Fetch',7,34),
('Contract_Approve_Reject',33,7),
('Create role',1,3),
('Create User',11,3),
('Create_User_Display_Table',0,10),
('Customer_Fetch_API',0,0),
('Edit_Role',4,3),
('Edit_User',11,3),
('Forgot_API',1,3),
('Gate_Pass_Doc_F4_API',5,1),
('Gate_Pass_Fetch_API',7,27),
('Gate_Pass_Save_API',27,2),
('Get_Plant',0,0),
('Get_Search_Term',0,0),
('GET_USER_PLANT',0,0),
('IMW_PMU_FETCH_API',6,38),
('IWM_PMU_EDIT_API',38,2),
('Login_API',2,15),
('Material_Fetch_API',3,21),
('Material_Save_API',23,3),
('MIGO_CANCEL',3,2),
('MIGO_Check_API',3,10),
('MIGO_Fetch_API',5,37),
('MIGO_POST_API',50,4),
('PMUA_APPROVE_API',48,2),
('PMUA_FETCH_API',7,48),
('PMUA_REJECT_API',48,2),
('PO_CANCEL_REJECT',2,4),
('PO_CANCEL_RELEASE',3,4),
('PO_GET_API',5,7),
('PO_REJECT_API',3,2),
('PO_Release_API',4,4),
('PR_CANCEL_REJECT',2,0),
('PR_CANCEL_RELEASE',5,0),
('PR_Reject_API',6,2),
('PR_Release_API',6,2),
('PR_Release_Multiple_Fetch_API',5,25),
('Price_Approval_Fetch',2,18),
('Price_Approve_Reject',18,3),
('Sales_Approval_Fetch',7,24),
('Sales_Order_Approve_Reject',23,8),
('Service_Certificate_Approve_Reject',40,2),
('SES_DELETE_API',2,4),
('SES_FETCH_API',26,29),
('SES_REJECT_API',3,4),
('SES_RELEASE_API',3,4),
('Sevice_Certificate_Fetch',9,39),
('ZGP_CANCEL_REPORT',17,2),
('ZGP_FETCH_REPORT',12,0),
('ZMC_Cancel_Report',37,2),
('ZMC_FETCH_REPORT',8,28),
('ZMIRS_DOC_F4_API',1,1),
('ZNFA_APPROVE_API',7,8),
('ZNFA_APPROVE_GET_API',6,13),
('ZNFA_ATTACH_API',5,92),
('ZNFA_ATTACH_PRINT_API',92,0),
('ZNFA_Clarification_API',10,8),
('ZNFA_Click _API',6,129),
('ZNFA_Create_API',11,12),
('ZNFA_DISPLAY_CLARIFY_API',10,1),
('ZNFA_DISPLAY_GET_API',6,129),
('ZNFA_Fetch_API',1,6),
('ZNFA_NFA_GET_API',1,1),
('ZNFA_PRINT_API',6,0),
('ZNFA_RATINGS_F4s_API',0,0),
('ZNFA_REJECT_API',7,8),
('ZNFA_RELEASE_GET_API',6,13),
('ZNFA_SAVE_API',16,3)
)
select e.name,
       case when c.id is null then 'MISSING' else 'INACTIVE' end as problem
from expected e
left join public.sap_api_configs c on c.name = e.name
where c.id is null or c.is_active is not true
order by 1;

\echo '== 3. Values the sync needs that this database REJECTS (EMPTY = schema OK) =='
with used(tbl, col, val) as (values
('sap_api_configs','module','COMMON'),
('sap_api_configs','module','SD'),
('sap_api_configs','api_type','fetch'),
('sap_api_configs','auth_type','basic'),
('sap_api_configs','http_method','GET'),
('sap_api_configs','http_method','POST'),
('sap_api_configs','http_method','PUT'),
('sap_api_request_fields','source','column'),
('sap_api_request_fields','source','static'),
('role_permissions','action','approve'),
('role_permissions','action','create'),
('role_permissions','action','delete'),
('role_permissions','action','edit'),
('role_permissions','action','export'),
('role_permissions','action','view')
),
checks as (
  select cl.relname as tbl, pg_get_constraintdef(con.oid) as def
  from pg_constraint con
  join pg_class cl on cl.oid = con.conrelid
  join pg_namespace ns on ns.oid = cl.relnamespace
  where ns.nspname = 'public' and con.contype = 'c'
)
select u.tbl, u.col, u.val, ch.def as constraint_definition
from used u
join checks ch on ch.tbl = u.tbl and ch.def like '%(' || u.col || ' =%'
where position(quote_literal(u.val) in ch.def) = 0
order by 1, 2, 3;

\echo '== 4. APIs whose field-mapping counts differ from the reference (EMPTY = all match) =='
with expected(name, req_count, res_count) as (values
('90%_CUST_API',1,1),
('90%_CUSTNAME_API',1,1),
('BMW_Status_Report',9,42),
('Contract_Approval_Fetch',7,34),
('Contract_Approve_Reject',33,7),
('Create role',1,3),
('Create User',11,3),
('Create_User_Display_Table',0,10),
('Customer_Fetch_API',0,0),
('Edit_Role',4,3),
('Edit_User',11,3),
('Forgot_API',1,3),
('Gate_Pass_Doc_F4_API',5,1),
('Gate_Pass_Fetch_API',7,27),
('Gate_Pass_Save_API',27,2),
('Get_Plant',0,0),
('Get_Search_Term',0,0),
('GET_USER_PLANT',0,0),
('IMW_PMU_FETCH_API',6,38),
('IWM_PMU_EDIT_API',38,2),
('Login_API',2,15),
('Material_Fetch_API',3,21),
('Material_Save_API',23,3),
('MIGO_CANCEL',3,2),
('MIGO_Check_API',3,10),
('MIGO_Fetch_API',5,37),
('MIGO_POST_API',50,4),
('PMUA_APPROVE_API',48,2),
('PMUA_FETCH_API',7,48),
('PMUA_REJECT_API',48,2),
('PO_CANCEL_REJECT',2,4),
('PO_CANCEL_RELEASE',3,4),
('PO_GET_API',5,7),
('PO_REJECT_API',3,2),
('PO_Release_API',4,4),
('PR_CANCEL_REJECT',2,0),
('PR_CANCEL_RELEASE',5,0),
('PR_Reject_API',6,2),
('PR_Release_API',6,2),
('PR_Release_Multiple_Fetch_API',5,25),
('Price_Approval_Fetch',2,18),
('Price_Approve_Reject',18,3),
('Sales_Approval_Fetch',7,24),
('Sales_Order_Approve_Reject',23,8),
('Service_Certificate_Approve_Reject',40,2),
('SES_DELETE_API',2,4),
('SES_FETCH_API',26,29),
('SES_REJECT_API',3,4),
('SES_RELEASE_API',3,4),
('Sevice_Certificate_Fetch',9,39),
('ZGP_CANCEL_REPORT',17,2),
('ZGP_FETCH_REPORT',12,0),
('ZMC_Cancel_Report',37,2),
('ZMC_FETCH_REPORT',8,28),
('ZMIRS_DOC_F4_API',1,1),
('ZNFA_APPROVE_API',7,8),
('ZNFA_APPROVE_GET_API',6,13),
('ZNFA_ATTACH_API',5,92),
('ZNFA_ATTACH_PRINT_API',92,0),
('ZNFA_Clarification_API',10,8),
('ZNFA_Click _API',6,129),
('ZNFA_Create_API',11,12),
('ZNFA_DISPLAY_CLARIFY_API',10,1),
('ZNFA_DISPLAY_GET_API',6,129),
('ZNFA_Fetch_API',1,6),
('ZNFA_NFA_GET_API',1,1),
('ZNFA_PRINT_API',6,0),
('ZNFA_RATINGS_F4s_API',0,0),
('ZNFA_REJECT_API',7,8),
('ZNFA_RELEASE_GET_API',6,13),
('ZNFA_SAVE_API',16,3)
)
select e.name,
       e.req_count as expected_request_fields,
       (select count(*) from public.sap_api_request_fields r where r.config_id = c.id) as actual_request_fields,
       e.res_count as expected_response_fields,
       (select count(*) from public.sap_api_response_fields s where s.config_id = c.id) as actual_response_fields
from expected e
join public.sap_api_configs c on c.name = e.name
where (select count(*) from public.sap_api_request_fields r where r.config_id = c.id) <> e.req_count
   or (select count(*) from public.sap_api_response_fields s where s.config_id = c.id) <> e.res_count
order by 1;

\echo '== 5. Extra APIs on this server that are not in the reference (informational) =='
with expected(name, req_count, res_count) as (values
('90%_CUST_API',1,1),
('90%_CUSTNAME_API',1,1),
('BMW_Status_Report',9,42),
('Contract_Approval_Fetch',7,34),
('Contract_Approve_Reject',33,7),
('Create role',1,3),
('Create User',11,3),
('Create_User_Display_Table',0,10),
('Customer_Fetch_API',0,0),
('Edit_Role',4,3),
('Edit_User',11,3),
('Forgot_API',1,3),
('Gate_Pass_Doc_F4_API',5,1),
('Gate_Pass_Fetch_API',7,27),
('Gate_Pass_Save_API',27,2),
('Get_Plant',0,0),
('Get_Search_Term',0,0),
('GET_USER_PLANT',0,0),
('IMW_PMU_FETCH_API',6,38),
('IWM_PMU_EDIT_API',38,2),
('Login_API',2,15),
('Material_Fetch_API',3,21),
('Material_Save_API',23,3),
('MIGO_CANCEL',3,2),
('MIGO_Check_API',3,10),
('MIGO_Fetch_API',5,37),
('MIGO_POST_API',50,4),
('PMUA_APPROVE_API',48,2),
('PMUA_FETCH_API',7,48),
('PMUA_REJECT_API',48,2),
('PO_CANCEL_REJECT',2,4),
('PO_CANCEL_RELEASE',3,4),
('PO_GET_API',5,7),
('PO_REJECT_API',3,2),
('PO_Release_API',4,4),
('PR_CANCEL_REJECT',2,0),
('PR_CANCEL_RELEASE',5,0),
('PR_Reject_API',6,2),
('PR_Release_API',6,2),
('PR_Release_Multiple_Fetch_API',5,25),
('Price_Approval_Fetch',2,18),
('Price_Approve_Reject',18,3),
('Sales_Approval_Fetch',7,24),
('Sales_Order_Approve_Reject',23,8),
('Service_Certificate_Approve_Reject',40,2),
('SES_DELETE_API',2,4),
('SES_FETCH_API',26,29),
('SES_REJECT_API',3,4),
('SES_RELEASE_API',3,4),
('Sevice_Certificate_Fetch',9,39),
('ZGP_CANCEL_REPORT',17,2),
('ZGP_FETCH_REPORT',12,0),
('ZMC_Cancel_Report',37,2),
('ZMC_FETCH_REPORT',8,28),
('ZMIRS_DOC_F4_API',1,1),
('ZNFA_APPROVE_API',7,8),
('ZNFA_APPROVE_GET_API',6,13),
('ZNFA_ATTACH_API',5,92),
('ZNFA_ATTACH_PRINT_API',92,0),
('ZNFA_Clarification_API',10,8),
('ZNFA_Click _API',6,129),
('ZNFA_Create_API',11,12),
('ZNFA_DISPLAY_CLARIFY_API',10,1),
('ZNFA_DISPLAY_GET_API',6,129),
('ZNFA_Fetch_API',1,6),
('ZNFA_NFA_GET_API',1,1),
('ZNFA_PRINT_API',6,0),
('ZNFA_RATINGS_F4s_API',0,0),
('ZNFA_REJECT_API',7,8),
('ZNFA_RELEASE_GET_API',6,13),
('ZNFA_SAVE_API',16,3)
)
select c.name, c.is_active
from public.sap_api_configs c
where not exists (select 1 from expected e where e.name = c.name)
order by 1;
