/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedHistoryRouteImport } from './routes/_authenticated/history'
import { Route as AuthenticatedInboxIndexRouteImport } from './routes/_authenticated/inbox.index'
import { Route as AuthenticatedSdScSoRouteImport } from './routes/_authenticated/sd.sc-so'
import { Route as AuthenticatedSdSalesOrderRouteImport } from './routes/_authenticated/sd.sales-order'
import { Route as AuthenticatedSdPriceRouteImport } from './routes/_authenticated/sd.price'
import { Route as AuthenticatedSdContractRouteImport } from './routes/_authenticated/sd.contract'
import { Route as AuthenticatedSdBmwStatusReportRouteImport } from './routes/_authenticated/sd.bmw-status-report'
import { Route as AuthenticatedInboxModuleRouteImport } from './routes/_authenticated/inbox.$module'
import { Route as AuthenticatedApprovalIdRouteImport } from './routes/_authenticated/approval.$id'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin.users'
import { Route as AuthenticatedAdminStrategiesRouteImport } from './routes/_authenticated/admin.strategies'
import { Route as AuthenticatedAdminIntegrationsRouteImport } from './routes/_authenticated/admin.integrations'
import { Route as AuthenticatedAdminSapApiIndexRouteImport } from './routes/_authenticated/admin.sap-api.index'
import { Route as ApiPublicMiddlewareLogRouteImport } from './routes/api/public/middleware/log'
import { Route as ApiPublicMiddlewareConfigRouteImport } from './routes/api/public/middleware/config'
import { Route as ApiPublicHooksSapSyncRouteImport } from './routes/api/public/hooks/sap-sync'
import { Route as AuthenticatedAdminSapApiIdRouteImport } from './routes/_authenticated/admin.sap-api.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedHistoryRoute = AuthenticatedHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedInboxIndexRoute = AuthenticatedInboxIndexRouteImport.update({
  id: '/inbox/',
  path: '/inbox/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSdScSoRoute = AuthenticatedSdScSoRouteImport.update({
  id: '/sd/sc-so',
  path: '/sd/sc-so',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSdSalesOrderRoute =
  AuthenticatedSdSalesOrderRouteImport.update({
    id: '/sd/sales-order',
    path: '/sd/sales-order',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSdPriceRoute = AuthenticatedSdPriceRouteImport.update({
  id: '/sd/price',
  path: '/sd/price',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSdContractRoute = AuthenticatedSdContractRouteImport.update({
  id: '/sd/contract',
  path: '/sd/contract',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSdBmwStatusReportRoute =
  AuthenticatedSdBmwStatusReportRouteImport.update({
    id: '/sd/bmw-status-report',
    path: '/sd/bmw-status-report',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInboxModuleRoute =
  AuthenticatedInboxModuleRouteImport.update({
    id: '/inbox/$module',
    path: '/inbox/$module',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedApprovalIdRoute = AuthenticatedApprovalIdRouteImport.update({
  id: '/approval/$id',
  path: '/approval/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminStrategiesRoute =
  AuthenticatedAdminStrategiesRouteImport.update({
    id: '/admin/strategies',
    path: '/admin/strategies',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminIntegrationsRoute =
  AuthenticatedAdminIntegrationsRouteImport.update({
    id: '/admin/integrations',
    path: '/admin/integrations',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminSapApiIndexRoute =
  AuthenticatedAdminSapApiIndexRouteImport.update({
    id: '/admin/sap-api/',
    path: '/admin/sap-api/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const ApiPublicMiddlewareLogRoute = ApiPublicMiddlewareLogRouteImport.update({
  id: '/api/public/middleware/log',
  path: '/api/public/middleware/log',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMiddlewareConfigRoute =
  ApiPublicMiddlewareConfigRouteImport.update({
    id: '/api/public/middleware/config',
    path: '/api/public/middleware/config',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksSapSyncRoute = ApiPublicHooksSapSyncRouteImport.update({
  id: '/api/public/hooks/sap-sync',
  path: '/api/public/hooks/sap-sync',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminSapApiIdRoute =
  AuthenticatedAdminSapApiIdRouteImport.update({
    id: '/admin/sap-api/$id',
    path: '/admin/sap-api/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/admin/integrations': typeof AuthenticatedAdminIntegrationsRoute
  '/admin/strategies': typeof AuthenticatedAdminStrategiesRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/approval/$id': typeof AuthenticatedApprovalIdRoute
  '/inbox/$module': typeof AuthenticatedInboxModuleRoute
  '/sd/bmw-status-report': typeof AuthenticatedSdBmwStatusReportRoute
  '/sd/contract': typeof AuthenticatedSdContractRoute
  '/sd/price': typeof AuthenticatedSdPriceRoute
  '/sd/sales-order': typeof AuthenticatedSdSalesOrderRoute
  '/sd/sc-so': typeof AuthenticatedSdScSoRoute
  '/inbox/': typeof AuthenticatedInboxIndexRoute
  '/admin/sap-api/$id': typeof AuthenticatedAdminSapApiIdRoute
  '/api/public/hooks/sap-sync': typeof ApiPublicHooksSapSyncRoute
  '/api/public/middleware/config': typeof ApiPublicMiddlewareConfigRoute
  '/api/public/middleware/log': typeof ApiPublicMiddlewareLogRoute
  '/admin/sap-api/': typeof AuthenticatedAdminSapApiIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/admin/integrations': typeof AuthenticatedAdminIntegrationsRoute
  '/admin/strategies': typeof AuthenticatedAdminStrategiesRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/approval/$id': typeof AuthenticatedApprovalIdRoute
  '/inbox/$module': typeof AuthenticatedInboxModuleRoute
  '/sd/bmw-status-report': typeof AuthenticatedSdBmwStatusReportRoute
  '/sd/contract': typeof AuthenticatedSdContractRoute
  '/sd/price': typeof AuthenticatedSdPriceRoute
  '/sd/sales-order': typeof AuthenticatedSdSalesOrderRoute
  '/sd/sc-so': typeof AuthenticatedSdScSoRoute
  '/inbox': typeof AuthenticatedInboxIndexRoute
  '/admin/sap-api/$id': typeof AuthenticatedAdminSapApiIdRoute
  '/api/public/hooks/sap-sync': typeof ApiPublicHooksSapSyncRoute
  '/api/public/middleware/config': typeof ApiPublicMiddlewareConfigRoute
  '/api/public/middleware/log': typeof ApiPublicMiddlewareLogRoute
  '/admin/sap-api': typeof AuthenticatedAdminSapApiIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/history': typeof AuthenticatedHistoryRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/admin/integrations': typeof AuthenticatedAdminIntegrationsRoute
  '/_authenticated/admin/strategies': typeof AuthenticatedAdminStrategiesRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/approval/$id': typeof AuthenticatedApprovalIdRoute
  '/_authenticated/inbox/$module': typeof AuthenticatedInboxModuleRoute
  '/_authenticated/sd/bmw-status-report': typeof AuthenticatedSdBmwStatusReportRoute
  '/_authenticated/sd/contract': typeof AuthenticatedSdContractRoute
  '/_authenticated/sd/price': typeof AuthenticatedSdPriceRoute
  '/_authenticated/sd/sales-order': typeof AuthenticatedSdSalesOrderRoute
  '/_authenticated/sd/sc-so': typeof AuthenticatedSdScSoRoute
  '/_authenticated/inbox/': typeof AuthenticatedInboxIndexRoute
  '/_authenticated/admin/sap-api/$id': typeof AuthenticatedAdminSapApiIdRoute
  '/api/public/hooks/sap-sync': typeof ApiPublicHooksSapSyncRoute
  '/api/public/middleware/config': typeof ApiPublicMiddlewareConfigRoute
  '/api/public/middleware/log': typeof ApiPublicMiddlewareLogRoute
  '/_authenticated/admin/sap-api/': typeof AuthenticatedAdminSapApiIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/history'
    | '/notifications'
    | '/settings'
    | '/admin/integrations'
    | '/admin/strategies'
    | '/admin/users'
    | '/approval/$id'
    | '/inbox/$module'
    | '/sd/bmw-status-report'
    | '/sd/contract'
    | '/sd/price'
    | '/sd/sales-order'
    | '/sd/sc-so'
    | '/inbox/'
    | '/admin/sap-api/$id'
    | '/api/public/hooks/sap-sync'
    | '/api/public/middleware/config'
    | '/api/public/middleware/log'
    | '/admin/sap-api/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/history'
    | '/notifications'
    | '/settings'
    | '/admin/integrations'
    | '/admin/strategies'
    | '/admin/users'
    | '/approval/$id'
    | '/inbox/$module'
    | '/sd/bmw-status-report'
    | '/sd/contract'
    | '/sd/price'
    | '/sd/sales-order'
    | '/sd/sc-so'
    | '/inbox'
    | '/admin/sap-api/$id'
    | '/api/public/hooks/sap-sync'
    | '/api/public/middleware/config'
    | '/api/public/middleware/log'
    | '/admin/sap-api'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/history'
    | '/_authenticated/notifications'
    | '/_authenticated/settings'
    | '/_authenticated/admin/integrations'
    | '/_authenticated/admin/strategies'
    | '/_authenticated/admin/users'
    | '/_authenticated/approval/$id'
    | '/_authenticated/inbox/$module'
    | '/_authenticated/sd/bmw-status-report'
    | '/_authenticated/sd/contract'
    | '/_authenticated/sd/price'
    | '/_authenticated/sd/sales-order'
    | '/_authenticated/sd/sc-so'
    | '/_authenticated/inbox/'
    | '/_authenticated/admin/sap-api/$id'
    | '/api/public/hooks/sap-sync'
    | '/api/public/middleware/config'
    | '/api/public/middleware/log'
    | '/_authenticated/admin/sap-api/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiPublicHooksSapSyncRoute: typeof ApiPublicHooksSapSyncRoute
  ApiPublicMiddlewareConfigRoute: typeof ApiPublicMiddlewareConfigRoute
  ApiPublicMiddlewareLogRoute: typeof ApiPublicMiddlewareLogRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/history': {
      id: '/_authenticated/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AuthenticatedHistoryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inbox/': {
      id: '/_authenticated/inbox/'
      path: '/inbox'
      fullPath: '/inbox/'
      preLoaderRoute: typeof AuthenticatedInboxIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/sd/sc-so': {
      id: '/_authenticated/sd/sc-so'
      path: '/sd/sc-so'
      fullPath: '/sd/sc-so'
      preLoaderRoute: typeof AuthenticatedSdScSoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/sd/sales-order': {
      id: '/_authenticated/sd/sales-order'
      path: '/sd/sales-order'
      fullPath: '/sd/sales-order'
      preLoaderRoute: typeof AuthenticatedSdSalesOrderRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/sd/price': {
      id: '/_authenticated/sd/price'
      path: '/sd/price'
      fullPath: '/sd/price'
      preLoaderRoute: typeof AuthenticatedSdPriceRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/sd/contract': {
      id: '/_authenticated/sd/contract'
      path: '/sd/contract'
      fullPath: '/sd/contract'
      preLoaderRoute: typeof AuthenticatedSdContractRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/sd/bmw-status-report': {
      id: '/_authenticated/sd/bmw-status-report'
      path: '/sd/bmw-status-report'
      fullPath: '/sd/bmw-status-report'
      preLoaderRoute: typeof AuthenticatedSdBmwStatusReportRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inbox/$module': {
      id: '/_authenticated/inbox/$module'
      path: '/inbox/$module'
      fullPath: '/inbox/$module'
      preLoaderRoute: typeof AuthenticatedInboxModuleRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/approval/$id': {
      id: '/_authenticated/approval/$id'
      path: '/approval/$id'
      fullPath: '/approval/$id'
      preLoaderRoute: typeof AuthenticatedApprovalIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/strategies': {
      id: '/_authenticated/admin/strategies'
      path: '/admin/strategies'
      fullPath: '/admin/strategies'
      preLoaderRoute: typeof AuthenticatedAdminStrategiesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/integrations': {
      id: '/_authenticated/admin/integrations'
      path: '/admin/integrations'
      fullPath: '/admin/integrations'
      preLoaderRoute: typeof AuthenticatedAdminIntegrationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/sap-api/': {
      id: '/_authenticated/admin/sap-api/'
      path: '/admin/sap-api'
      fullPath: '/admin/sap-api/'
      preLoaderRoute: typeof AuthenticatedAdminSapApiIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/middleware/log': {
      id: '/api/public/middleware/log'
      path: '/api/public/middleware/log'
      fullPath: '/api/public/middleware/log'
      preLoaderRoute: typeof ApiPublicMiddlewareLogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/middleware/config': {
      id: '/api/public/middleware/config'
      path: '/api/public/middleware/config'
      fullPath: '/api/public/middleware/config'
      preLoaderRoute: typeof ApiPublicMiddlewareConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/sap-sync': {
      id: '/api/public/hooks/sap-sync'
      path: '/api/public/hooks/sap-sync'
      fullPath: '/api/public/hooks/sap-sync'
      preLoaderRoute: typeof ApiPublicHooksSapSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/sap-api/$id': {
      id: '/_authenticated/admin/sap-api/$id'
      path: '/admin/sap-api/$id'
      fullPath: '/admin/sap-api/$id'
      preLoaderRoute: typeof AuthenticatedAdminSapApiIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedHistoryRoute: typeof AuthenticatedHistoryRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedAdminIntegrationsRoute: typeof AuthenticatedAdminIntegrationsRoute
  AuthenticatedAdminStrategiesRoute: typeof AuthenticatedAdminStrategiesRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedApprovalIdRoute: typeof AuthenticatedApprovalIdRoute
  AuthenticatedInboxModuleRoute: typeof AuthenticatedInboxModuleRoute
  AuthenticatedSdBmwStatusReportRoute: typeof AuthenticatedSdBmwStatusReportRoute
  AuthenticatedSdContractRoute: typeof AuthenticatedSdContractRoute
  AuthenticatedSdPriceRoute: typeof AuthenticatedSdPriceRoute
  AuthenticatedSdSalesOrderRoute: typeof AuthenticatedSdSalesOrderRoute
  AuthenticatedSdScSoRoute: typeof AuthenticatedSdScSoRoute
  AuthenticatedInboxIndexRoute: typeof AuthenticatedInboxIndexRoute
  AuthenticatedAdminSapApiIdRoute: typeof AuthenticatedAdminSapApiIdRoute
  AuthenticatedAdminSapApiIndexRoute: typeof AuthenticatedAdminSapApiIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedHistoryRoute: AuthenticatedHistoryRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedAdminIntegrationsRoute: AuthenticatedAdminIntegrationsRoute,
  AuthenticatedAdminStrategiesRoute: AuthenticatedAdminStrategiesRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedApprovalIdRoute: AuthenticatedApprovalIdRoute,
  AuthenticatedInboxModuleRoute: AuthenticatedInboxModuleRoute,
  AuthenticatedSdBmwStatusReportRoute: AuthenticatedSdBmwStatusReportRoute,
  AuthenticatedSdContractRoute: AuthenticatedSdContractRoute,
  AuthenticatedSdPriceRoute: AuthenticatedSdPriceRoute,
  AuthenticatedSdSalesOrderRoute: AuthenticatedSdSalesOrderRoute,
  AuthenticatedSdScSoRoute: AuthenticatedSdScSoRoute,
  AuthenticatedInboxIndexRoute: AuthenticatedInboxIndexRoute,
  AuthenticatedAdminSapApiIdRoute: AuthenticatedAdminSapApiIdRoute,
  AuthenticatedAdminSapApiIndexRoute: AuthenticatedAdminSapApiIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiPublicHooksSapSyncRoute: ApiPublicHooksSapSyncRoute,
  ApiPublicMiddlewareConfigRoute: ApiPublicMiddlewareConfigRoute,
  ApiPublicMiddlewareLogRoute: ApiPublicMiddlewareLogRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
